---
title: "Experiment"
author: "Rakha Hafish Setiawan"
date: "`r Sys.Date()`"
output: html_document
---

```{r echo = FALSE, include = FALSE, message=FALSE}
library(tidyverse)
library(writexl)
library(sqldf)
MyCars = readxl::read_excel("C:/Users/Rakha Hafish S/Downloads/Electric Car Sales by Model in USA.xlsx")
```

```{r}
MyCarsTemp = MyCars %>%
  select(everything(), -3) %>%
  gather(Date, Sales, 3:98) %>%
  mutate(Sales = ifelse(is.na(Sales), 0, Sales))
```

```{r}
MyDates = MyCars %>%
  select(everything()) %>%
  gather(Dates, Sales, 4:99) %>%
  select(Dates) %>%
  apply(2, FUN = str_remove_all, " ") %>%
  data.frame() %>%
  apply(2, FUN = str_remove_all, "-") %>%
  data.frame() %>%
  apply(2, FUN = str_to_title) %>%
  data.frame() 
```

```{r}
CarsFixed = MyCarsTemp %>%
  bind_cols(MyDates) %>%
  select(Make, Model, Dates, Sales) %>%
  mutate(Year = if_else(grepl("12", Dates), 2012,
                if_else(grepl("13", Dates), 2013,
                if_else(grepl("14", Dates), 2014,
                if_else(grepl("15", Dates), 2015,
                if_else(grepl("16", Dates), 2016,
                if_else(grepl("17", Dates), 2017,
                if_else(grepl("18", Dates), 2018, 2019)))))))) %>%
  select(Make, Model, Year, Sales) %>%
  write.csv("C://Users//Rakha Hafish S//Desktop//Personal Projects//CarSales.csv")
```

```{r}
sqldf::sqldf("SELECT Make,
             MAX(Sales) FROM CarsFixed 
             GROUP BY Make
             ORDER BY MAX(Sales) DESC")
```




